name: Java Maven Build & Docker Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # - name: Build with Maven
    #   run: mvn clean package

    - name: Build Docker Image
      run: docker build -t dockerimage .


# sudo groupadd docker  # Ensure the docker group exists
# sudo usermod -aG docker $(whoami)  # Add the current user
# sudo usermod -aG docker ubuntu  # Add the 'ubuntu' user (or any specific user)
# sudo chmod 666 /var/run/docker.sock



   
